export const serviceTypes = [
    "Oil Change",
    "Tire Rotation",
    "Brake Service",
    "Wheel Alignment",
    "Battery Replacement",
    "Transmission Service",
    "Cooling System Service",
    "Suspension Repair",
    "Exhaust System Repair",
    "Fuel System Cleaning",
    "Timing Belt Replacement",
    "Air Filter Replacement",
    "Cabin Air Filter Replacement",
    "Spark Plug Replacement",
    "Headlight/Taillight Replacement",
    "Wiper Blade Replacement",
    "Engine Diagnostics & Tune-up",
    "Other",
];